name: mickey
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.17
  - pip=23.2.1
  - pip:
    - einops==0.6.1
    - lazy-loader==0.3
    - lightning-utilities==0.9.0
    - matplotlib==3.7.2
    - numpy==1.24.4
    - omegaconf==2.3.0
    - open3d==0.17.0
    - opencv-python==4.8.0.74
    - protobuf==4.23.4
    - pytorch-lightning==2.0.6
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - timm==0.6.7
    - torch==2.0.1
    - torchmetrics==1.0.2
    - torchvision==0.15.2
    - tqdm==4.65.1
    - transforms3d==0.4.1
    - xformers==0.0.20
    - yacs==0.1.8
    - pillow==10.0.0
    - scipy==1.10.1
    - pyrender==0.1.45
    - trimesh==4.0.2
